### ISSUE TITLE
auto-apply as-single no-input   fails always

### ISSUE THREAD

**Issue by tvld** [elreco/vue-tailwind-datepicker#56]
Consider this
```vue
<template>
  <div>
    <vue-tailwind-datepicker v-model="dateValue" i18n="nl" no-input as-single  />
    {{ dateValue }}
  </div>
  >
</template>

<script setup lang="ts">
  import { ref } from 'vue'
  import VueTailwindDatepicker from 'vue-tailwind-datepicker'

  const dateValue = ref({
    startDate: '',
    endDate: ''
  })
</script>
```

This fails with:
```log

runtime-core.esm-bundler.js:218 Uncaught TypeError: k is not a function
    at R (entry.6e4f86f4.mjs:1749:9)
    at e.noInput.P.value.createVNode.onUpdate:date.h2.<computed>.h2.<computed> (entry.6e4f86f4.mjs:2129:64)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at emit$1 (runtime-core.esm-bundler.js:711:9)
    at runtime-core.esm-bundler.js:7371:53
    at onClick (entry.6e4f86f4.mjs:193:31)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:354:13)

runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of component event handler 
  at <Calendar calendar= {month: 'jan', year: 2023, date: ƒ, years: ƒ, onPrevious: ƒ, …} weeks= (7) ['ma.', 'di.', 'wo.', 'do.', 'vr.', 'za.', 'zo.'] as-range=false  ... > 
  at <VueTailwindDatePicker modelValue= {startDate: '2023-01-10 11:25:19'} onUpdate:modelValue=fn i18n="nl"  ... > 
  at <DatePickerTests onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <TestLayout> 
  at <App>
warn2 @ runtime-core.esm-bundler.js:38
logError @ runtime-core.esm-bundler.js:212
handleError @ runtime-core.esm-bundler.js:204
callWithErrorHandling @ runtime-core.esm-bundler.js:158
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
emit$1 @ runtime-core.esm-bundler.js:711
(anonymous) @ runtime-core.esm-bundler.js:7371
onClick @ entry.6e4f86f4.mjs:193
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
invoker @ runtime-dom.esm-bundler.js:354
runtime-core.esm-bundler.js:38 [Vue warn]: Unhandled error during execution of native event handler 
  at <TransitionGroup enter-from-class="opacity-0" enter-to-class="opacity-100" enter-active-class="transition-opacity ease-out duration-300"  ... > 
  at <Calendar calendar= {month: 'jan', year: 2023, date: ƒ, years: ƒ, onPrevious: ƒ, …} weeks= (7) ['ma.', 'di.', 'wo.', 'do.', 'vr.', 'za.', 'zo.'] as-range=false  ... > 
  at <VueTailwindDatePicker modelValue= {startDate: '2023-01-10 11:25:19'} onUpdate:modelValue=fn i18n="nl"  ... > 
  at <DatePickerTests onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > > 
  at <RouterView> 
  at <TestLayout> 
  at <App>
```

This works:
```ts
<template>
  <div>
    <vue-tailwind-datepicker v-model="dateValue" i18n="nl" no-input as-single :auto-apply="false" />
    {{ dateValue }}
  </div>
</template>

<script setup lang="ts">
  import { ref } from 'vue'
  import VueTailwindDatepicker from 'vue-tailwind-datepicker'

  const dateValue = ref('')
</script>

```

**Comment by elreco** [comment]
Take the latest version and it works
